id: P007996
initial_creation_type: ocr
created_at: 23/03/2020
last_modified_at: 2021-12-17 12:54:02.925578
source_metadata:
  id: bdr:W1KG24859
  title: ལེགས་འགྲུབ་ཡོང་བ་ཇི་ལྟར་བྱེད། རི་མོའི་ལམ་ནས་པིར་ཀའི་ཚིའི་སྐོར་གླེང་བ།
  author: ''
  volumes:
    2fcb4b7523774045b0e845d094302210:
      image_group_id: I1KG24861
      title: Volume 1 of legs 'grub yong ba ji ltar byed/_ri mo'i lam nas pir ka'i
        tshi'i skor gleng ba/
      volume_number: 1
      total_pages: 188
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
