id: P007996
initial_creation_type: ocr
source_metadata:
  id: bdr:W1KG24859
  title: ལེགས་འགྲུབ་ཡོང་བ་ཇི་ལྟར་བྱེད། རི་མོའི་ལམ་ནས་པིར་ཀའི་ཚིའི་སྐོར་གླེང་བ།
  author: ''
  volumes:
    9cb4ca6090994723968e9f923685bad7:
      image_group_id: I1KG24861
      title: ''
      volume_number: 1
      total_pages: 188
ebook_metadata:
  title: ལེགས་འགྲུབ་ཡོང་བ་ཇི་ལྟར་བྱེད། རི་མོའི་ལམ་ནས་པིར་ཀའི་ཚིའི་སྐོར་གླེང་བ།
  author: ''
  sku: P007996
  cover: cover.jpg
  layers:
  - pagination
